### ISSUE TITLE
Could you add a wire schema, please?

### ISSUE THREAD

**Issue by bguban** [mongoose-os-libs/arduino-adafruit-htu21df#1]
Hi guys, I'm a newbie in an electronic. Could you, please, add a wire schema to a documentation, because I have no idea how to connect my HTU21 sensor to my nodemcu module. And it will be great to have a C++ example, because I have a rest of code (communication with server) in C. 
Thank you a lot.

**Comment by pedalPusher68** [comment]
I'd suggest you visit a site like [Adafruit](https://learn.adafruit.com/adafruit-huzzah32-esp32-feather/pinouts?view=all) or [this one ](https://learn.adafruit.com/adafruit-htu21d-f-temperature-humidity-sensor/assembly?view=all).  Teaching how to create a complete prototype circuit and developing examples beyond what is in the Readme.md file is beyond the scope of my intent.  One other point... the Javascript example running on Mongoose OS on your hardware is really the easiest way to build a circuit and code for it.
