### ISSUE TITLE
Unused variable error

### ISSUE THREAD

**Issue by bguban** [mongoose-os-libs/arduino-adafruit-htu21df#2]
Hi guys, I tried to compile an example from README.md and got an error:
```
/fwbuild-volumes/latest/apps/demo-js/esp8266/build_contexts/build_ctx_363100358/libs/arduino-adafruit-htu21df/src/Adafruit_HTU21DF.cpp:89:13: error: unused variable 'crc' [-Werror=unused-variable]
     uint8_t crc = Wire.read();
             ^
```

**Comment by pedalPusher68** [comment]
I cloned this repository this morning and did a '`mos build`'  I got the same warning and the library compiled fine producing lib.a in the build directory.

```
Target build/objs/moslib/libmoslib.a is built successfully
Lib saved to build/lib.a

```

I'd make sure you read through the sample Mongoose OS developer documentation;  get your development environment setup and verify it works for you with the simplest of examples (e.g. demo c, etc.);  and try again.
