### ISSUE TITLE
Adafruit_HTU21DF.cpp:89:13: error: unused variable 'crc'

### ISSUE THREAD

**Issue by tyriis** [mongoose-os-libs/arduino-adafruit-htu21df#3]
I got the following error when tryiing to include the library and rebuild the firmware in the web ui.

... arduino-adafruit-htu21df/src/Adafruit_HTU21DF.cpp:89:13: error: unused variable 'crc' [-Werror=unused-variable]
[Jan  1 13:52:33.028]      uint8_t crc = Wire.read();
[Jan  1 13:52:33.028]              ^
[Jan  1 13:52:33.028] cc1plus: all warnings being treated as errors

**Comment by cpq** [comment]
Try to disable warnings in your mos.yml, per
https://mongoose-os.com/docs/book/build.html#cflags-cxxflags

**Comment by pedalPusher68** [comment]
I checked in a change to address this - rather than disable warnings, I cast the offending variable declaration to void - warning (error) ceases to be reported on build of library.
